# Form implementation generated from reading ui file './UI/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 668)
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(25, 25,30);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.widget)
        self.side_menu.setMinimumSize(QtCore.QSize(90, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(90, 16777215))
        self.side_menu.setStyleSheet("")
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_widget = QtWidgets.QWidget(self.side_menu)
        self.button_widget.setMinimumSize(QtCore.QSize(0, 350))
        self.button_widget.setObjectName("button_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.button_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_button = QtWidgets.QPushButton(self.button_widget)
        self.file_button.setMinimumSize(QtCore.QSize(0, 90))
        self.file_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.file_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UI/../Icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.file_button.setIcon(icon)
        self.file_button.setIconSize(QtCore.QSize(45, 45))
        self.file_button.setObjectName("file_button")
        self.verticalLayout_3.addWidget(self.file_button)
        self.mask_button = QtWidgets.QPushButton(self.button_widget)
        self.mask_button.setMinimumSize(QtCore.QSize(0, 90))
        self.mask_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.mask_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./UI/../Icons/mask.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mask_button.setIcon(icon1)
        self.mask_button.setIconSize(QtCore.QSize(45, 45))
        self.mask_button.setObjectName("mask_button")
        self.verticalLayout_3.addWidget(self.mask_button)
        self.clip_button = QtWidgets.QPushButton(self.button_widget)
        self.clip_button.setMinimumSize(QtCore.QSize(0, 90))
        self.clip_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.clip_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./UI/../Icons/clip.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clip_button.setIcon(icon2)
        self.clip_button.setIconSize(QtCore.QSize(45, 45))
        self.clip_button.setObjectName("clip_button")
        self.verticalLayout_3.addWidget(self.clip_button)
        self.verticalLayout_2.addWidget(self.button_widget, 0, QtCore.Qt.Alignment.AlignTop)
        self.horizontalLayout.addWidget(self.side_menu)
        self.vertica_divider_2 = QtWidgets.QWidget(self.widget)
        self.vertica_divider_2.setMinimumSize(QtCore.QSize(3, 0))
        self.vertica_divider_2.setMaximumSize(QtCore.QSize(3, 16777215))
        self.vertica_divider_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 1px;\n"
"}")
        self.vertica_divider_2.setObjectName("vertica_divider_2")
        self.horizontalLayout.addWidget(self.vertica_divider_2)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 218, 628))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.file_page = QtWidgets.QWidget()
        self.file_page.setStyleSheet("")
        self.file_page.setObjectName("file_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.file_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_title = QtWidgets.QLabel(self.file_page)
        self.file_title.setMinimumSize(QtCore.QSize(0, 90))
        self.file_title.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.file_title.setFont(font)
        self.file_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.file_title.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.file_title.setObjectName("file_title")
        self.verticalLayout_4.addWidget(self.file_title)
        self.widget_2 = QtWidgets.QWidget(self.file_page)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(12, 0, 12, 12)
        self.verticalLayout_7.setSpacing(30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mask_dir_button = QtWidgets.QPushButton(self.widget_2)
        self.mask_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.mask_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.mask_dir_button.setObjectName("mask_dir_button")
        self.verticalLayout_7.addWidget(self.mask_dir_button)
        self.image_dir_button = QtWidgets.QPushButton(self.widget_2)
        self.image_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.image_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.image_dir_button.setObjectName("image_dir_button")
        self.verticalLayout_7.addWidget(self.image_dir_button)
        self.output_dir_button = QtWidgets.QPushButton(self.widget_2)
        self.output_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.output_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.output_dir_button.setObjectName("output_dir_button")
        self.verticalLayout_7.addWidget(self.output_dir_button)
        self.verticalLayout_4.addWidget(self.widget_2, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 6)
        self.stackedWidget.addWidget(self.file_page)
        self.mask_page = QtWidgets.QWidget()
        self.mask_page.setObjectName("mask_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mask_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mask_title = QtWidgets.QLabel(self.mask_page)
        self.mask_title.setMinimumSize(QtCore.QSize(0, 90))
        self.mask_title.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mask_title.setFont(font)
        self.mask_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.mask_title.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.mask_title.setObjectName("mask_title")
        self.verticalLayout_5.addWidget(self.mask_title)
        self.widget_3 = QtWidgets.QWidget(self.mask_page)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 800))
        self.widget_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.change_pen_button = QtWidgets.QPushButton(self.widget_5)
        self.change_pen_button.setMinimumSize(QtCore.QSize(0, 65))
        self.change_pen_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.change_pen_button.setObjectName("change_pen_button")
        self.verticalLayout_8.addWidget(self.change_pen_button)
        self.color_button = QtWidgets.QPushButton(self.widget_5)
        self.color_button.setMinimumSize(QtCore.QSize(0, 65))
        self.color_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.color_button.setObjectName("color_button")
        self.verticalLayout_8.addWidget(self.color_button)
        self.dialate_button = QtWidgets.QPushButton(self.widget_5)
        self.dialate_button.setMinimumSize(QtCore.QSize(0, 65))
        self.dialate_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.dialate_button.setObjectName("dialate_button")
        self.verticalLayout_8.addWidget(self.dialate_button)
        self.erode_button = QtWidgets.QPushButton(self.widget_5)
        self.erode_button.setMinimumSize(QtCore.QSize(0, 65))
        self.erode_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.erode_button.setObjectName("erode_button")
        self.verticalLayout_8.addWidget(self.erode_button)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout.setObjectName("gridLayout")
        self.primarr_color_widget = QtWidgets.QWidget(self.widget_6)
        self.primarr_color_widget.setMinimumSize(QtCore.QSize(80, 80))
        self.primarr_color_widget.setMaximumSize(QtCore.QSize(80, 80))
        self.primarr_color_widget.setStyleSheet("QWidget{\n"
"    border: 5px solid rgb(57, 58, 73);\n"
"    border-radius: 40px;\n"
"}")
        self.primarr_color_widget.setObjectName("primarr_color_widget")
        self.gridLayout.addWidget(self.primarr_color_widget, 0, 0, 1, 1)
        self.secondary_color_widget = QtWidgets.QWidget(self.widget_6)
        self.secondary_color_widget.setMinimumSize(QtCore.QSize(40, 40))
        self.secondary_color_widget.setMaximumSize(QtCore.QSize(40, 40))
        self.secondary_color_widget.setStyleSheet("QWidget{\n"
"    border: 5px solid rgb(57, 58, 73);\n"
"    border-radius: 20px;\n"
"}")
        self.secondary_color_widget.setObjectName("secondary_color_widget")
        self.gridLayout.addWidget(self.secondary_color_widget, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_6, 0, QtCore.Qt.Alignment.AlignTop)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalSlider = QtWidgets.QSlider(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider.sizePolicy().hasHeightForWidth())
        self.verticalSlider.setSizePolicy(sizePolicy)
        self.verticalSlider.setMinimumSize(QtCore.QSize(10, 0))
        self.verticalSlider.setMaximumSize(QtCore.QSize(10, 16777215))
        self.verticalSlider.setStyleSheet("QSlider::handle:vertical{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(50, 51, 64);\n"
"}\n"
"QSlider::handle:vertical:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(70, 72, 92);\n"
"}\n"
"QSlider::add-page:vertical{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::sub-page:vertical{\n"
"    background-color: rgb(12, 12, 16);\n"
"    border-radius: 5px;\n"
"}")
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setProperty("value", 100)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientations.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_2.addWidget(self.verticalSlider)
        self.verticalLayout_5.addWidget(self.widget_3, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_5.setStretch(0, 1)
        self.stackedWidget.addWidget(self.mask_page)
        self.clip_page = QtWidgets.QWidget()
        self.clip_page.setObjectName("clip_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.clip_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.file_title_2 = QtWidgets.QLabel(self.clip_page)
        self.file_title_2.setMinimumSize(QtCore.QSize(0, 90))
        self.file_title_2.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.file_title_2.setFont(font)
        self.file_title_2.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.file_title_2.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.file_title_2.setObjectName("file_title_2")
        self.verticalLayout_6.addWidget(self.file_title_2)
        self.widget_4 = QtWidgets.QWidget(self.clip_page)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_7 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 350))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 500))
        self.widget_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_12.setContentsMargins(12, 0, 12, 10)
        self.verticalLayout_12.setSpacing(30)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.generate_masks_button = QtWidgets.QPushButton(self.widget_7)
        self.generate_masks_button.setMinimumSize(QtCore.QSize(0, 65))
        self.generate_masks_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.generate_masks_button.setObjectName("generate_masks_button")
        self.verticalLayout_12.addWidget(self.generate_masks_button)
        self.view_clip_details_button = QtWidgets.QPushButton(self.widget_7)
        self.view_clip_details_button.setMinimumSize(QtCore.QSize(0, 65))
        self.view_clip_details_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.view_clip_details_button.setObjectName("view_clip_details_button")
        self.verticalLayout_12.addWidget(self.view_clip_details_button)
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_10)
        self.widget_8.setMinimumSize(QtCore.QSize(170, 170))
        self.widget_8.setMaximumSize(QtCore.QSize(150, 150))
        self.widget_8.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 85px;\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.doubleSpinBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    color: white;\n"
"}")
        self.doubleSpinBox.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_11.addWidget(self.doubleSpinBox)
        self.label = QtWidgets.QLabel(self.widget_8)
        self.label.setMaximumSize(QtCore.QSize(140, 20))
        self.label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label, 0, QtCore.Qt.Alignment.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_12.addWidget(self.widget_10)
        self.widget_10.raise_()
        self.generate_masks_button.raise_()
        self.view_clip_details_button.raise_()
        self.verticalLayout_10.addWidget(self.widget_7)
        self.verticalLayout_9.addWidget(self.widget_9, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 6)
        self.stackedWidget.addWidget(self.clip_page)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.vertica_divider = QtWidgets.QWidget(self.widget)
        self.vertica_divider.setMinimumSize(QtCore.QSize(3, 0))
        self.vertica_divider.setMaximumSize(QtCore.QSize(3, 16777215))
        self.vertica_divider.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 1px;\n"
"}")
        self.vertica_divider.setObjectName("vertica_divider")
        self.horizontalLayout.addWidget(self.vertica_divider)
        self.image_widget = QtWidgets.QWidget(self.widget)
        self.image_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.image_widget.setObjectName("image_widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.image_widget)
        self.verticalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_11 = QtWidgets.QWidget(self.image_widget)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.image_widget)
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_12.setStyleSheet("")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previous_frame_button = QtWidgets.QPushButton(self.widget_12)
        self.previous_frame_button.setMinimumSize(QtCore.QSize(40, 30))
        self.previous_frame_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.previous_frame_button.setObjectName("previous_frame_button")
        self.horizontalLayout_5.addWidget(self.previous_frame_button)
        self.frame_slider = QtWidgets.QSlider(self.widget_12)
        self.frame_slider.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_slider.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(50, 51, 64);\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(70, 72, 92);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_slider.setOrientation(QtCore.Qt.Orientations.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout_5.addWidget(self.frame_slider)
        self.next_frame_button = QtWidgets.QPushButton(self.widget_12)
        self.next_frame_button.setMinimumSize(QtCore.QSize(40, 30))
        self.next_frame_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.next_frame_button.setObjectName("next_frame_button")
        self.horizontalLayout_5.addWidget(self.next_frame_button)
        self.verticalLayout_13.addWidget(self.widget_12)
        self.horizontalLayout.addWidget(self.image_widget)
        self.side_menu.raise_()
        self.image_widget.raise_()
        self.vertica_divider.raise_()
        self.vertica_divider_2.raise_()
        self.scrollArea.raise_()
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_title.setText(_translate("MainWindow", "File Information"))
        self.mask_dir_button.setText(_translate("MainWindow", "Get Mask Directory"))
        self.image_dir_button.setText(_translate("MainWindow", "Get Image Directory"))
        self.output_dir_button.setText(_translate("MainWindow", "Set Output Directory"))
        self.mask_title.setText(_translate("MainWindow", "Mask Settings"))
        self.change_pen_button.setText(_translate("MainWindow", "Change Pen"))
        self.color_button.setText(_translate("MainWindow", "Change Pen Color"))
        self.dialate_button.setText(_translate("MainWindow", "Dialate Mask"))
        self.erode_button.setText(_translate("MainWindow", "Erode Mask"))
        self.verticalSlider.setToolTip(_translate("MainWindow", "Change view opacity.  This will not affect the final output."))
        self.file_title_2.setText(_translate("MainWindow", "Clip Information"))
        self.generate_masks_button.setText(_translate("MainWindow", "Generate Clip Masks"))
        self.view_clip_details_button.setText(_translate("MainWindow", "View Clip Details"))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.label.setText(_translate("MainWindow", "Generation Progress"))
        self.previous_frame_button.setText(_translate("MainWindow", "<<"))
        self.next_frame_button.setText(_translate("MainWindow", ">>"))
