# Form implementation generated from reading ui file './Assets/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 766)
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(25, 25,30);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.widget)
        self.side_menu.setMinimumSize(QtCore.QSize(90, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(90, 16777215))
        self.side_menu.setStyleSheet("")
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_widget = QtWidgets.QWidget(self.side_menu)
        self.button_widget.setMinimumSize(QtCore.QSize(0, 350))
        self.button_widget.setObjectName("button_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.button_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_button = QtWidgets.QPushButton(self.button_widget)
        self.file_button.setMinimumSize(QtCore.QSize(0, 90))
        self.file_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.file_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/Icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.file_button.setIcon(icon)
        self.file_button.setIconSize(QtCore.QSize(45, 45))
        self.file_button.setObjectName("file_button")
        self.verticalLayout_3.addWidget(self.file_button)
        self.mask_button = QtWidgets.QPushButton(self.button_widget)
        self.mask_button.setMinimumSize(QtCore.QSize(0, 90))
        self.mask_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.mask_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Assets/Icons/mask.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mask_button.setIcon(icon1)
        self.mask_button.setIconSize(QtCore.QSize(45, 45))
        self.mask_button.setObjectName("mask_button")
        self.verticalLayout_3.addWidget(self.mask_button)
        self.clip_button = QtWidgets.QPushButton(self.button_widget)
        self.clip_button.setMinimumSize(QtCore.QSize(0, 90))
        self.clip_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(25, 25,30);\n"
"    border-radius: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(35, 35, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.clip_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Assets/Icons/clip.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clip_button.setIcon(icon2)
        self.clip_button.setIconSize(QtCore.QSize(45, 45))
        self.clip_button.setObjectName("clip_button")
        self.verticalLayout_3.addWidget(self.clip_button)
        self.verticalLayout_2.addWidget(self.button_widget, 0, QtCore.Qt.Alignment.AlignTop)
        self.horizontalLayout.addWidget(self.side_menu)
        self.vertical_divider_side_menu = QtWidgets.QWidget(self.widget)
        self.vertical_divider_side_menu.setMinimumSize(QtCore.QSize(3, 0))
        self.vertical_divider_side_menu.setMaximumSize(QtCore.QSize(3, 16777215))
        self.vertical_divider_side_menu.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 1px;\n"
"}")
        self.vertical_divider_side_menu.setObjectName("vertical_divider_side_menu")
        self.horizontalLayout.addWidget(self.vertical_divider_side_menu)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Orientations.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 388, 684))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.file_page = QtWidgets.QWidget()
        self.file_page.setStyleSheet("")
        self.file_page.setObjectName("file_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.file_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_title = QtWidgets.QLabel(self.file_page)
        self.file_title.setMinimumSize(QtCore.QSize(0, 90))
        self.file_title.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.file_title.setFont(font)
        self.file_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.file_title.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.file_title.setObjectName("file_title")
        self.verticalLayout_4.addWidget(self.file_title)
        self.file_button_container = QtWidgets.QWidget(self.file_page)
        self.file_button_container.setMinimumSize(QtCore.QSize(200, 0))
        self.file_button_container.setObjectName("file_button_container")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.file_button_container)
        self.verticalLayout_7.setContentsMargins(12, 0, 12, 12)
        self.verticalLayout_7.setSpacing(30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mask_dir_button = QtWidgets.QPushButton(self.file_button_container)
        self.mask_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.mask_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.mask_dir_button.setObjectName("mask_dir_button")
        self.verticalLayout_7.addWidget(self.mask_dir_button)
        self.image_dir_button = QtWidgets.QPushButton(self.file_button_container)
        self.image_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.image_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.image_dir_button.setObjectName("image_dir_button")
        self.verticalLayout_7.addWidget(self.image_dir_button)
        self.output_dir_button = QtWidgets.QPushButton(self.file_button_container)
        self.output_dir_button.setMinimumSize(QtCore.QSize(0, 65))
        self.output_dir_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.output_dir_button.setObjectName("output_dir_button")
        self.verticalLayout_7.addWidget(self.output_dir_button)
        self.save_project_button = QtWidgets.QPushButton(self.file_button_container)
        self.save_project_button.setMinimumSize(QtCore.QSize(0, 65))
        self.save_project_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.save_project_button.setObjectName("save_project_button")
        self.verticalLayout_7.addWidget(self.save_project_button)
        self.open_project_button = QtWidgets.QPushButton(self.file_button_container)
        self.open_project_button.setMinimumSize(QtCore.QSize(0, 65))
        self.open_project_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.open_project_button.setObjectName("open_project_button")
        self.verticalLayout_7.addWidget(self.open_project_button)
        self.verticalLayout_4.addWidget(self.file_button_container, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 6)
        self.stackedWidget.addWidget(self.file_page)
        self.mask_page = QtWidgets.QWidget()
        self.mask_page.setObjectName("mask_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mask_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mask_title = QtWidgets.QLabel(self.mask_page)
        self.mask_title.setMinimumSize(QtCore.QSize(0, 90))
        self.mask_title.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mask_title.setFont(font)
        self.mask_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.mask_title.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.mask_title.setObjectName("mask_title")
        self.verticalLayout_5.addWidget(self.mask_title)
        self.mask_settings_container = QtWidgets.QWidget(self.mask_page)
        self.mask_settings_container.setMaximumSize(QtCore.QSize(16777215, 800))
        self.mask_settings_container.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mask_settings_container.setObjectName("mask_settings_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mask_settings_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mask_buttons_container = QtWidgets.QWidget(self.mask_settings_container)
        self.mask_buttons_container.setObjectName("mask_buttons_container")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mask_buttons_container)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(25)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.change_pen_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.change_pen_button.setMinimumSize(QtCore.QSize(0, 40))
        self.change_pen_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.change_pen_button.setObjectName("change_pen_button")
        self.verticalLayout_8.addWidget(self.change_pen_button)
        self.color_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.color_button.setMinimumSize(QtCore.QSize(0, 40))
        self.color_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.color_button.setObjectName("color_button")
        self.verticalLayout_8.addWidget(self.color_button)
        self.dialate_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.dialate_button.setMinimumSize(QtCore.QSize(0, 40))
        self.dialate_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.dialate_button.setObjectName("dialate_button")
        self.verticalLayout_8.addWidget(self.dialate_button)
        self.erode_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.erode_button.setMinimumSize(QtCore.QSize(0, 40))
        self.erode_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.erode_button.setObjectName("erode_button")
        self.verticalLayout_8.addWidget(self.erode_button)
        self.resolve_frame_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.resolve_frame_button.setMinimumSize(QtCore.QSize(0, 40))
        self.resolve_frame_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.resolve_frame_button.setObjectName("resolve_frame_button")
        self.verticalLayout_8.addWidget(self.resolve_frame_button)
        self.clear_changes_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.clear_changes_button.setMinimumSize(QtCore.QSize(0, 40))
        self.clear_changes_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.clear_changes_button.setObjectName("clear_changes_button")
        self.verticalLayout_8.addWidget(self.clear_changes_button)
        self.save_current_button = QtWidgets.QPushButton(self.mask_buttons_container)
        self.save_current_button.setMinimumSize(QtCore.QSize(0, 40))
        self.save_current_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.save_current_button.setObjectName("save_current_button")
        self.verticalLayout_8.addWidget(self.save_current_button)
        self.color_indicator_container = QtWidgets.QWidget(self.mask_buttons_container)
        self.color_indicator_container.setObjectName("color_indicator_container")
        self.gridLayout = QtWidgets.QGridLayout(self.color_indicator_container)
        self.gridLayout.setObjectName("gridLayout")
        self.primary_color_widget = QtWidgets.QWidget(self.color_indicator_container)
        self.primary_color_widget.setMinimumSize(QtCore.QSize(80, 80))
        self.primary_color_widget.setMaximumSize(QtCore.QSize(80, 80))
        self.primary_color_widget.setStyleSheet("QWidget{\n"
"    border: 5px solid rgb(57, 58, 73);\n"
"    border-radius: 40px;\n"
"}")
        self.primary_color_widget.setObjectName("primary_color_widget")
        self.gridLayout.addWidget(self.primary_color_widget, 0, 0, 1, 1)
        self.secondary_color_widget = QtWidgets.QWidget(self.color_indicator_container)
        self.secondary_color_widget.setMinimumSize(QtCore.QSize(40, 40))
        self.secondary_color_widget.setMaximumSize(QtCore.QSize(40, 40))
        self.secondary_color_widget.setStyleSheet("QWidget{\n"
"    border: 5px solid rgb(57, 58, 73);\n"
"    border-radius: 20px;\n"
"}")
        self.secondary_color_widget.setObjectName("secondary_color_widget")
        self.gridLayout.addWidget(self.secondary_color_widget, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.color_indicator_container, 0, QtCore.Qt.Alignment.AlignTop)
        self.horizontalLayout_2.addWidget(self.mask_buttons_container)
        self.verticalSlider = QtWidgets.QSlider(self.mask_settings_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider.sizePolicy().hasHeightForWidth())
        self.verticalSlider.setSizePolicy(sizePolicy)
        self.verticalSlider.setMinimumSize(QtCore.QSize(10, 0))
        self.verticalSlider.setMaximumSize(QtCore.QSize(10, 16777215))
        self.verticalSlider.setStyleSheet("QSlider::handle:vertical{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(50, 51, 64);\n"
"}\n"
"QSlider::handle:vertical:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(70, 72, 92);\n"
"}\n"
"QSlider::add-page:vertical{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::sub-page:vertical{\n"
"    background-color: rgb(12, 12, 16);\n"
"    border-radius: 5px;\n"
"}")
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setProperty("value", 100)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientations.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_2.addWidget(self.verticalSlider)
        self.verticalLayout_5.addWidget(self.mask_settings_container, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_5.setStretch(0, 1)
        self.stackedWidget.addWidget(self.mask_page)
        self.clip_page = QtWidgets.QWidget()
        self.clip_page.setObjectName("clip_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.clip_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.clip_title = QtWidgets.QLabel(self.clip_page)
        self.clip_title.setMinimumSize(QtCore.QSize(0, 90))
        self.clip_title.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clip_title.setFont(font)
        self.clip_title.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.clip_title.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.clip_title.setObjectName("clip_title")
        self.verticalLayout_6.addWidget(self.clip_title)
        self.clip_information_container = QtWidgets.QWidget(self.clip_page)
        self.clip_information_container.setObjectName("clip_information_container")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.clip_information_container)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.clip_operations_container = QtWidgets.QWidget(self.clip_information_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clip_operations_container.sizePolicy().hasHeightForWidth())
        self.clip_operations_container.setSizePolicy(sizePolicy)
        self.clip_operations_container.setMinimumSize(QtCore.QSize(0, 350))
        self.clip_operations_container.setMaximumSize(QtCore.QSize(16777215, 500))
        self.clip_operations_container.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.clip_operations_container.setStyleSheet("")
        self.clip_operations_container.setObjectName("clip_operations_container")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.clip_operations_container)
        self.verticalLayout_12.setContentsMargins(12, 0, 12, 10)
        self.verticalLayout_12.setSpacing(30)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.generate_masks_button = QtWidgets.QPushButton(self.clip_operations_container)
        self.generate_masks_button.setMinimumSize(QtCore.QSize(0, 65))
        self.generate_masks_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.generate_masks_button.setObjectName("generate_masks_button")
        self.verticalLayout_12.addWidget(self.generate_masks_button)
        self.view_clip_details_button = QtWidgets.QPushButton(self.clip_operations_container)
        self.view_clip_details_button.setMinimumSize(QtCore.QSize(0, 65))
        self.view_clip_details_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.view_clip_details_button.setObjectName("view_clip_details_button")
        self.verticalLayout_12.addWidget(self.view_clip_details_button)
        self.set_iterations_button = QtWidgets.QPushButton(self.clip_operations_container)
        self.set_iterations_button.setMinimumSize(QtCore.QSize(0, 65))
        self.set_iterations_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.set_iterations_button.setObjectName("set_iterations_button")
        self.verticalLayout_12.addWidget(self.set_iterations_button)
        self.generation_status_container = QtWidgets.QWidget(self.clip_operations_container)
        self.generation_status_container.setObjectName("generation_status_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.generation_status_container)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.generation_background = QtWidgets.QWidget(self.generation_status_container)
        self.generation_background.setMinimumSize(QtCore.QSize(170, 170))
        self.generation_background.setMaximumSize(QtCore.QSize(150, 150))
        self.generation_background.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 85px;\n"
"}")
        self.generation_background.setObjectName("generation_background")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.generation_background)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.generation_status = QtWidgets.QDoubleSpinBox(self.generation_background)
        self.generation_status.setMinimumSize(QtCore.QSize(0, 0))
        self.generation_status.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.generation_status.setFont(font)
        self.generation_status.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.generation_status.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.generation_status.setStyleSheet("QDoubleSpinBox{\n"
"    color: white;\n"
"}")
        self.generation_status.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.generation_status.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.generation_status.setMaximum(100.0)
        self.generation_status.setProperty("value", 0.0)
        self.generation_status.setObjectName("generation_status")
        self.verticalLayout_11.addWidget(self.generation_status)
        self.generation_status_label = QtWidgets.QLabel(self.generation_background)
        self.generation_status_label.setMaximumSize(QtCore.QSize(140, 20))
        self.generation_status_label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.generation_status_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.generation_status_label.setObjectName("generation_status_label")
        self.verticalLayout_11.addWidget(self.generation_status_label, 0, QtCore.Qt.Alignment.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.generation_background)
        self.verticalLayout_12.addWidget(self.generation_status_container)
        self.generation_status_container.raise_()
        self.generate_masks_button.raise_()
        self.view_clip_details_button.raise_()
        self.set_iterations_button.raise_()
        self.verticalLayout_9.addWidget(self.clip_operations_container)
        self.verticalLayout_6.addWidget(self.clip_information_container, 0, QtCore.Qt.Alignment.AlignTop)
        self.verticalLayout_6.setStretch(0, 1)
        self.stackedWidget.addWidget(self.clip_page)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.workspace = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspace.sizePolicy().hasHeightForWidth())
        self.workspace.setSizePolicy(sizePolicy)
        self.workspace.setMinimumSize(QtCore.QSize(0, 0))
        self.workspace.setObjectName("workspace")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.workspace)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(25)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.vertical_divider_workspace = QtWidgets.QWidget(self.workspace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertical_divider_workspace.sizePolicy().hasHeightForWidth())
        self.vertical_divider_workspace.setSizePolicy(sizePolicy)
        self.vertical_divider_workspace.setMinimumSize(QtCore.QSize(3, 0))
        self.vertical_divider_workspace.setMaximumSize(QtCore.QSize(3, 16777215))
        self.vertical_divider_workspace.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.vertical_divider_workspace.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 1px;\n"
"}")
        self.vertical_divider_workspace.setObjectName("vertical_divider_workspace")
        self.horizontalLayout_6.addWidget(self.vertical_divider_workspace)
        self.mask_operations_container = QtWidgets.QWidget(self.workspace)
        self.mask_operations_container.setObjectName("mask_operations_container")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.mask_operations_container)
        self.verticalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_display_container = QtWidgets.QWidget(self.mask_operations_container)
        self.frame_display_container.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_display_container.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_display_container.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_display_container.setObjectName("frame_display_container")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_display_container)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_label = QtWidgets.QLabel(self.frame_display_container)
        self.frame_label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.frame_label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout_8.addWidget(self.frame_label)
        self.frame_spin_box = QtWidgets.QSpinBox(self.frame_display_container)
        self.frame_spin_box.setStyleSheet("QSpinBox{\n"
"    color: white;\n"
"}")
        self.frame_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.frame_spin_box.setObjectName("frame_spin_box")
        self.horizontalLayout_8.addWidget(self.frame_spin_box)
        self.verticalLayout_14.addWidget(self.frame_display_container)
        self.paint_interface_container = QtWidgets.QWidget(self.mask_operations_container)
        self.paint_interface_container.setObjectName("paint_interface_container")
        self.verticalLayout_14.addWidget(self.paint_interface_container)
        self.frame_operations_container = QtWidgets.QWidget(self.mask_operations_container)
        self.frame_operations_container.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_operations_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_operations_container.setStyleSheet("")
        self.frame_operations_container.setObjectName("frame_operations_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_operations_container)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previous_frame_button = QtWidgets.QPushButton(self.frame_operations_container)
        self.previous_frame_button.setMinimumSize(QtCore.QSize(40, 30))
        self.previous_frame_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.previous_frame_button.setObjectName("previous_frame_button")
        self.horizontalLayout_5.addWidget(self.previous_frame_button)
        self.frame_slider = QtWidgets.QSlider(self.frame_operations_container)
        self.frame_slider.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_slider.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(50, 51, 64);\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(70, 72, 92);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"    background-color: rgb(35, 35, 44);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_slider.setOrientation(QtCore.Qt.Orientations.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout_5.addWidget(self.frame_slider)
        self.next_frame_button = QtWidgets.QPushButton(self.frame_operations_container)
        self.next_frame_button.setMinimumSize(QtCore.QSize(40, 30))
        self.next_frame_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(33,33, 40);\n"
"    color:white;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 37, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47, 48, 60);\n"
"}")
        self.next_frame_button.setObjectName("next_frame_button")
        self.horizontalLayout_5.addWidget(self.next_frame_button)
        self.verticalLayout_14.addWidget(self.frame_operations_container)
        self.horizontalLayout_6.addWidget(self.mask_operations_container)
        self.horizontalLayout.addWidget(self.splitter)
        self.splitter.raise_()
        self.side_menu.raise_()
        self.vertical_divider_side_menu.raise_()
        self.verticalLayout.addWidget(self.widget)
        self.info_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_bar.sizePolicy().hasHeightForWidth())
        self.info_bar.setSizePolicy(sizePolicy)
        self.info_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.info_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.info_bar.setStyleSheet("QWidget{\n"
"    background-color: rgb(33,33, 40);\n"
"}\n"
"")
        self.info_bar.setObjectName("info_bar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.info_bar)
        self.horizontalLayout_7.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.info_label = QtWidgets.QLabel(self.info_bar)
        self.info_label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.horizontalLayout_7.addWidget(self.info_label)
        self.verticalLayout.addWidget(self.info_bar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 999, 22))
        self.menuBar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.menuBar.setStyleSheet("")
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.action_save_file = QtGui.QAction(MainWindow)
        self.action_save_file.setObjectName("action_save_file")
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save_as = QtGui.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_manual = QtGui.QAction(MainWindow)
        self.action_manual.setObjectName("action_manual")
        self.menuFile.addAction(self.action_save_file)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save_as)
        self.menuHelp.addAction(self.action_manual)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_title.setText(_translate("MainWindow", "File Information"))
        self.mask_dir_button.setText(_translate("MainWindow", "Get Mask Directory"))
        self.image_dir_button.setText(_translate("MainWindow", "Get Image Directory"))
        self.output_dir_button.setText(_translate("MainWindow", "Set Output Directory"))
        self.save_project_button.setText(_translate("MainWindow", "Save Project File"))
        self.open_project_button.setText(_translate("MainWindow", "Open Project File"))
        self.mask_title.setText(_translate("MainWindow", "Mask Settings"))
        self.change_pen_button.setText(_translate("MainWindow", "Change Pen"))
        self.color_button.setText(_translate("MainWindow", "Change Pen Color"))
        self.dialate_button.setText(_translate("MainWindow", "Dialate Mask"))
        self.erode_button.setText(_translate("MainWindow", "Erode Mask"))
        self.resolve_frame_button.setText(_translate("MainWindow", "Recalculate Current"))
        self.clear_changes_button.setText(_translate("MainWindow", "Clear Changes"))
        self.save_current_button.setText(_translate("MainWindow", "Save Current"))
        self.verticalSlider.setToolTip(_translate("MainWindow", "Change view opacity.  This will not affect the final output."))
        self.clip_title.setText(_translate("MainWindow", "Clip Information"))
        self.generate_masks_button.setText(_translate("MainWindow", "Generate Clip Masks"))
        self.view_clip_details_button.setText(_translate("MainWindow", "View Clip Details"))
        self.set_iterations_button.setText(_translate("MainWindow", "Set Crabcut Iterations"))
        self.generation_status.setSuffix(_translate("MainWindow", "%"))
        self.generation_status_label.setText(_translate("MainWindow", "Generation Progress"))
        self.frame_label.setText(_translate("MainWindow", "Frame:"))
        self.previous_frame_button.setText(_translate("MainWindow", "<<"))
        self.next_frame_button.setText(_translate("MainWindow", ">>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "help"))
        self.action_save_file.setText(_translate("MainWindow", "Save File"))
        self.action_save_file.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_open.setText(_translate("MainWindow", "Open..."))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save_as.setText(_translate("MainWindow", "Save As..."))
        self.action_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_manual.setText(_translate("MainWindow", "Manual"))
